// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = {
	'hello': string
	'explain': string

	/**
	 * Welcome to Svelte Fall Summit {year}
	 * @param {number} year
	 */
	//'HI': RequiredParams1<'year'>
}

export type TranslationFunctions = {
	'hello': () => LocalizedString
	'explain': () => LocalizedString
}

export type Formatters = {
	'simpleDate': (value: Date) => unknown
}
